### ISSUE TITLE
After logging out, the signout screen should go away

### ISSUE THREAD

**Issue by elliotBraem** [near-everything/canvas#4]
After logging out, the dropdown menu sticks around. It should go away if no context.accountId

<img width="393" alt="Screenshot 2023-11-20 at 10 17 22 PM" src="https://github.com/near-everything/canvas/assets/16282460/eb99cad0-8000-4d96-9ce4-90bd659c7e34">

**Comment by itexpert120** [comment]
i'll try to fix this

**Comment by elliotBraem** [comment]
Looks resolved now
